### ISSUE TITLE
NameError (uninitialized constant RedmineLoginAudit::Hooks::ControllerAccountSuccessAuthenticationAfterHook::LoginAudit)

### ISSUE THREAD

**Issue by Catlon** [martin-denizet/redmine_login_audit#18]
Hello,

I am running Redmine V3.1.1
I have just completed installation of this extension and after server reboot I am getting the following error: 

```
NameError (uninitialized constant RedmineLoginAudit::Hooks::ControllerAccountSuccessAuthenticationAfterHook::LoginAudit):
  lib/redmine/hook.rb:61:in `block (2 levels) in call_hook'
  lib/redmine/hook.rb:61:in `each'
  lib/redmine/hook.rb:61:in `block in call_hook'
  lib/redmine/hook.rb:58:in `tap'
  lib/redmine/hook.rb:58:in `call_hook'
  lib/redmine/hook.rb:162:in `call_hook'
  app/controllers/account_controller.rb:261:in `successful_authentication'
  app/controllers/account_controller.rb:203:in `password_authentication'
  app/controllers/account_controller.rb:189:in `authenticate_user'
  app/controllers/account_controller.rb:40:in `login'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'
```

This occurs right after the first login screen.

Can you help me?

C.

**Comment by martin-denizet** [comment]
Hello, thanks for reporting this issue. I'll try to look into it today.
I'm little confused about what could go wrong because I tested it against Redmine 3.1.1.
Would you mind joining Ruby version and list of installed plugins?
Cheers,

**Comment by Catlon** [comment]
Hello,
thanks for your quick response.
Here is the info I have:

**Plugins**
```
redmine_login_audit-master
redmine_people
redmine_wktime
```

**Gems**
```
Using rake 10.4.2
Using i18n 0.7.0
Using json 1.8.3
Using minitest 5.8.2
Using thread_safe 0.3.5
Using tzinfo 1.2.2
Using activesupport 4.2.4
Using builder 3.2.2
Using erubis 2.7.0
Using mini_portile 0.6.2
Using nokogiri 1.6.6.3
Using rails-deprecated_sanitizer 1.0.3
Using rails-dom-testing 1.0.7
Using loofah 2.0.3
Using rails-html-sanitizer 1.0.2
Using actionview 4.2.4
Using rack 1.6.4
Using rack-test 0.6.3
Using actionpack 4.2.4
Using globalid 0.3.6
Using activejob 4.2.4
Using mime-types 2.6.2
Using mail 2.6.3
Using actionmailer 4.2.4
Using actionpack-action_caching 1.1.1
Using actionpack-xml_parser 1.0.2
Using activemodel 4.2.4
Using arel 6.0.3
Using activerecord 4.2.4
Using bundler 1.10.6
Using coderay 1.1.0
Installing coffee-script-source 1.10.0
Installing execjs 2.6.0
Installing coffee-script 2.4.1
Using thor 0.19.1
Using railties 4.2.4
Installing coffee-rails 4.1.0
Using htmlentities 4.3.1
Using jquery-rails 3.1.4
Installing kaminari 0.16.3
Using mysql2 0.3.20
Using net-ldap 0.3.1
Using protected_attributes 1.1.3
Using ruby-openid 2.3.0
Using rack-openid 1.4.2
Using sprockets 3.4.0
Using sprockets-rails 2.3.3
Using rails 4.2.4
Using rbpdf 1.18.7
Using redcarpet 3.3.3
Using redmine_crm 0.0.20
Using request_store 1.0.5
Using rufus-scheduler 3.0.3
Using vcard 0.2.12
Installing wice_grid 3.5.0
```

**Comment by martin-denizet** [comment]
Rename _plugins/redmine_login_audit-master_ into _plugins/redmine_login_audit_ then restart your web server. That should do it.
Cheers,

**Comment by Catlon** [comment]
Yes that worked perfectly!
Thanks a lot!

**Comment by martin-denizet** [comment]
Good to hear! :+1:
