### ISSUE TITLE
Compatibility with OpenID login

### ISSUE THREAD

**Issue by g-teley** [martin-denizet/redmine_login_audit#37]
When using OpenID as logon, the system halts with error 500.

```
I, [2018-04-19T14:38:36.679721 #54632]  INFO -- : Completed 500 Internal Server Error in 43ms (ActiveRecord: 13.4ms)
F, [2018-04-19T14:38:36.681403 #54632] FATAL -- :
ArgumentError (wrong number of arguments (given 1, expected 0)):
  plugins/redmine_login_audit/lib/redmine_login_audit/account_controller_patch.rb:23:in `onthefly_creation_failed_with_login_audit'
  app/controllers/account_controller.rb:251:in `block (2 levels) in open_id_authenticate'
```
Environment:
  Redmine version                3.4.4.stable
  Ruby version                   2.4.3-p205 (2017-12-14) [amd64-freebsd11]
  Rails version                  4.2.10
  Environment                    production
  Database adapter               Mysql2
Redmine plugins:
...
  redmine_login_audit            0.3.3
...

**Comment by martin-denizet** [comment]
Thank you, I will look it up 👍

**Comment by martin-denizet** [comment]
Hello,
I pushed a patch in the develop branch, could you please test it? (I didn't write tests for OpenID yet...)
```
git checkout develop
git pull
```
You will also need to restart your Redmine instance.
Thanks!

**Comment by g-teley** [comment]
Hello Martin,

Looks like the problem is solved.
Thanks for the quick support!

Kind regards/
Met vriendelijke groet,
Guus Teley
(mobiel)

Op 20 apr. 2018 11:50 schreef "Martin Denizet" <notifications@github.com>:

Hello,
I pushed a patch in the develop branch, could you please test it? (I didn't
write tests for OpenID yet...)

git checkout develop
git pull

You will also need to restart your Redmine instance.
Thanks!

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/martin-denizet/redmine_login_audit/issues/37#issuecomment-383046337>,
or mute the thread
