### ISSUE TITLE
onthefly_creation_failed_with_login_audit

### ISSUE THREAD

**Issue by cooperchen** [martin-denizet/redmine_login_audit#38]
Hi, when I try to login with LDAP will get these message, how to fix them? 

ArgumentError (wrong number of arguments (given 2, expected 0)):                                                                                                                      
  plugins/redmine_login_audit/lib/redmine_login_audit/account_controller_patch.rb:23:in `onthefly_creation_failed_with_login_audit'                                                   
  app/controllers/account_controller.rb:215:in `password_authentication'                                                                                                              
  app/controllers/account_controller.rb:205:in `authenticate_user'                                                                                                                    
  app/controllers/account_controller.rb:38:in `login'                                                                                                                                 
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'

**Comment by cooperchen** [comment]
Solved, LDAP account has no email， onthefly will be error
