### ISSUE TITLE
Error accessing the administration page /login_audit

### ISSUE THREAD

**Issue by schildg** [martin-denizet/redmine_login_audit#40]
Hello, I recently installed redmine_login_audit v0.3.3 in a redmine v3.4.8 (stack bitnami), when I want to access the page / login_audit I get the following error:

I, [2019-02-26T10:06:15.695866 #5962]  INFO -- : Started GET "/login_audit" for 192.168.100.192 at 2019-02-26 10:06:15 -0300
I, [2019-02-26T10:06:15.702307 #5962]  INFO -- : Processing by LoginAuditController#index as HTML
I, [2019-02-26T10:06:15.722267 #5962]  INFO -- :   Current user: gschild (id=84)
I, [2019-02-26T10:06:15.760780 #5962]  INFO -- :   Rendered plugins/redmine_login_audit/app/views/login_audit/index.html.erb within layouts/admin (29.7ms)
I, [2019-02-26T10:06:15.761114 #5962]  INFO -- : Completed 500 Internal Server Error in 58ms (ActiveRecord: 5.6ms)
F, [2019-02-26T10:06:15.763849 #5962] FATAL -- :
LoadError (cannot load such file -- sass):
  config/initializers/10-patches.rb:221:in `rails_asset_id'
  config/initializers/10-patches.rb:200:in `asset_path_with_asset_id'
  app/helpers/application_helper.rb:1398:in `javascript_include_tag'
  plugins/redmine_login_audit/app/views/login_audit/index.html.erb:4:in `block in _cb3b8d9c6453ac2096453d4843522797'
  plugins/redmine_login_audit/app/views/login_audit/index.html.erb:1:in `_cb3b8d9c6453ac2096453d4843522797'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'
  plugins/redmine_dmsf/lib/redmine_dmsf/webdav/custom_middleware.rb:68:in `call'

Who is generating the error? redmine_dmsf or redmine_login_audit?

how can I solve that?

regards

**Comment by nlpguyz** [comment]
You can delete the javascript_include_tag line first from index.html.erb. The plugin should load. 

Then see how the plugin redmine_wice_grid loads the JS file and how to put assets in the plugin properly.
