### ISSUE TITLE
redmine-3.4.9 undefined method 'tag_options'

### ISSUE THREAD

**Issue by askifyouneed** [martin-denizet/redmine_login_audit#41]
Problem during migrate
```
# bundle exec rake redmine:plugins:migrate RAILS_ENV=production
(in /u01/redmine-3.4.9)
rake aborted!
NameError: undefined method `tag_options' for module `ActionView::Helpers::TagHelper'
Did you mean?  with_options
/usr/local/rvm/gems/ruby-2.6.0/gems/wice_grid-3.5.0/lib/wice/wice_grid_core_ext.rb:123:in `public'
/usr/local/rvm/gems/ruby-2.6.0/gems/wice_grid-3.5.0/lib/wice/wice_grid_core_ext.rb:123:in `<module:TagHelper>'
/usr/local/rvm/gems/ruby-2.6.0/gems/wice_grid-3.5.0/lib/wice/wice_grid_core_ext.rb:122:in `<module:Helpers>'
/usr/local/rvm/gems/ruby-2.6.0/gems/wice_grid-3.5.0/lib/wice/wice_grid_core_ext.rb:121:in `<module:ActionView>'
/usr/local/rvm/gems/ruby-2.6.0/gems/wice_grid-3.5.0/lib/wice/wice_grid_core_ext.rb:120:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.6.0/gems/wice_grid-3.5.0/lib/wice_grid.rb:2:in `require'
/usr/local/rvm/gems/ruby-2.6.0/gems/wice_grid-3.5.0/lib/wice_grid.rb:2:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.6.0/gems/bundler-1.17.3/lib/bundler/runtime.rb:81:in `require'
/usr/local/rvm/gems/ruby-2.6.0/gems/bundler-1.17.3/lib/bundler/runtime.rb:81:in `block (2 levels) in require'
/usr/local/rvm/gems/ruby-2.6.0/gems/bundler-1.17.3/lib/bundler/runtime.rb:76:in `each'
/usr/local/rvm/gems/ruby-2.6.0/gems/bundler-1.17.3/lib/bundler/runtime.rb:76:in `block in require'
/usr/local/rvm/gems/ruby-2.6.0/gems/bundler-1.17.3/lib/bundler/runtime.rb:65:in `each'
/usr/local/rvm/gems/ruby-2.6.0/gems/bundler-1.17.3/lib/bundler/runtime.rb:65:in `require'
/usr/local/rvm/gems/ruby-2.6.0/gems/bundler-1.17.3/lib/bundler.rb:114:in `require'
/u01/redmine-3.4.9/config/application.rb:5:in `<top (required)>'
/u01/redmine-3.4.9/Rakefile:5:in `require'
/u01/redmine-3.4.9/Rakefile:5:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.6.0/gems/bundler-1.17.3/lib/bundler/cli/exec.rb:74:in `load'
/usr/local/rvm/gems/ruby-2.6.0/gems/bundler-1.17.3/lib/bundler/cli/exec.rb:74:in `kernel_load'
/usr/local/rvm/gems/ruby-2.6.0/gems/bundler-1.17.3/lib/bundler/cli/exec.rb:28:in `run'
/usr/local/rvm/gems/ruby-2.6.0/gems/bundler-1.17.3/lib/bundler/cli.rb:463:in `exec'
/usr/local/rvm/gems/ruby-2.6.0/gems/bundler-1.17.3/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/usr/local/rvm/gems/ruby-2.6.0/gems/bundler-1.17.3/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/usr/local/rvm/gems/ruby-2.6.0/gems/bundler-1.17.3/lib/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
/usr/local/rvm/gems/ruby-2.6.0/gems/bundler-1.17.3/lib/bundler/cli.rb:27:in `dispatch'
/usr/local/rvm/gems/ruby-2.6.0/gems/bundler-1.17.3/lib/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
/usr/local/rvm/gems/ruby-2.6.0/gems/bundler-1.17.3/lib/bundler/cli.rb:18:in `start'
/usr/local/rvm/gems/ruby-2.6.0/gems/bundler-1.17.3/exe/bundle:30:in `block in <top (required)>'
/usr/local/rvm/gems/ruby-2.6.0/gems/bundler-1.17.3/lib/bundler/friendly_errors.rb:124:in `with_friendly_errors'
/usr/local/rvm/gems/ruby-2.6.0/gems/bundler-1.17.3/exe/bundle:22:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.6.0/bin/bundle:23:in `load'
/usr/local/rvm/gems/ruby-2.6.0/bin/bundle:23:in `<main>'
(See full trace by running task with --trace)
```

**Comment by nico-raynal** [comment]
Same problem...

RAILS_ENV=production rake db:migrate
rake aborted!
NameError: undefined method `tag_options' for module `ActionView::Helpers::TagHelper'
Did you mean?  with_options
/usr/share/gems/gems/wice_grid-3.5.0/lib/wice/wice_grid_core_ext.rb:123:in `public'
/usr/share/gems/gems/wice_grid-3.5.0/lib/wice/wice_grid_core_ext.rb:123:in `<module:TagHelper>'
/usr/share/gems/gems/wice_grid-3.5.0/lib/wice/wice_grid_core_ext.rb:122:in `<module:Helpers>'
/usr/share/gems/gems/wice_grid-3.5.0/lib/wice/wice_grid_core_ext.rb:121:in `<module:ActionView>'
/usr/share/gems/gems/wice_grid-3.5.0/lib/wice/wice_grid_core_ext.rb:120:in `<top (required)>'
/usr/share/gems/gems/activesupport-6.1.7/lib/active_support/dependencies.rb:332:in `require'
/usr/share/gems/gems/activesupport-6.1.7/lib/active_support/dependencies.rb:332:in `block in require'
/usr/share/gems/gems/activesupport-6.1.7/lib/active_support/dependencies.rb:299:in `load_dependency'
/usr/share/gems/gems/activesupport-6.1.7/lib/active_support/dependencies.rb:332:in `require'
/usr/share/gems/gems/wice_grid-3.5.0/lib/wice_grid.rb:2:in `<top (required)>'
/usr/local/share/gems/gems/bundler-2.4.19/lib/bundler/runtime.rb:60:in `require'
/usr/local/share/gems/gems/bundler-2.4.19/lib/bundler/runtime.rb:60:in `block (2 levels) in require'
/usr/local/share/gems/gems/bundler-2.4.19/lib/bundler/runtime.rb:55:in `each'
/usr/local/share/gems/gems/bundler-2.4.19/lib/bundler/runtime.rb:55:in `block in require'
/usr/local/share/gems/gems/bundler-2.4.19/lib/bundler/runtime.rb:44:in `each'
/usr/local/share/gems/gems/bundler-2.4.19/lib/bundler/runtime.rb:44:in `require'
/usr/local/share/gems/gems/bundler-2.4.19/lib/bundler.rb:187:in `require'
/appli/redmine-5.0.3/config/application.rb:20:in `<top (required)>'
<internal:/usr/share/rubygems/rubygems/core_ext/kernel_require.rb>:85:in `require'
<internal:/usr/share/rubygems/rubygems/core_ext/kernel_require.rb>:85:in `require'
/appli/redmine-5.0.3/Rakefile:5:in `<top (required)>'
/usr/share/gems/gems/rake-13.0.6/exe/rake:27:in `<top (required)>'
(See full trace by running task with --trace)
